# SPDX-License-Identifier: GPL-2.0
[package]
name = "kconfirm"
repository = "https://github.com/julianbraha/kconfirm"
license-file = "LICENSE"
description = "A static analysis tool for Kconfig"
keywords = ["kconfig", "static", "analysis", "detect", "smt"]
categories = ["development-tools", "config", "command-line-utilities"]
exclude = ["assets/", "findings/"]
version = "1.0.0"
edition = "2024"

[workspace]
members = [
    "kconfirm-lib",
    "kconfirm-cli",
    "kconfirm-linux",
    "kconfirm-desugar",
    "kconfirm-smt",
    "z3-ternary"]

[workspace.package]
rust-version = "1.85.0"

[workspace.dependencies]
# my fork
nom-kconfig = { git = "https://github.com/julianbraha/nom-kconfig", rev = "1870a9b234543dd4abdd984b849bc9030684f59f", default-features = false, features = [
    "display",
    "kconfiglib"
] }

log = "0.4"
env_logger = "0.11"
libc = "0.2"
z3 = { version = "0.20", features = ["z3_4_16"] }

[profile.release]
lto = true
codegen-units = 1
