# SPDX-License-Identifier: GPL-2.0
[package]
name = "kconfirm-smt"
version = "0.10.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
kconfirm-lib = { path = "../kconfirm-lib" }
kconfirm-linux = { path = "../kconfirm-linux" }

nom-kconfig = { workspace = true }
z3 = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

[features]
default = []
