[package]
name = "kconfirm-cli"
version = "0.9.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
kconfirm-lib = { path = "../kconfirm-lib", features = ["coreboot"] }
kconfirm-linux = { path = "../kconfirm-linux" }

nom-kconfig = { workspace = true, features = ["glob-wildcard"] }
log = { workspace = true }
clap = { version = "4.6", features = ["derive"] }
env_logger = "0.11"
